### ISSUE TITLE
Auth0 is not Mobile first.  Apps don’t work

### ISSUE THREAD

**Issue by jcook123** [mozilla-iam/auth0-custom-lock#29] opened 2018-02-21 22:00 UTC
Box app for example does not work on mobile devices.  Repeatable

**Comment by gene1wood** [comment] 2018-02-21 23:57
@jcook123 Are you seeing this when trying to login to multiple different SSO login sites, or just https://mozilla.box.com/ ?

**Comment by gdestuynder** [comment] 2018-02-22 01:47
I've been troubleshooting this with EUS and it turns out that's unrelated to the new login experience.
Box updated their SAML setup with Auth0 today as well, and something went wrong (and thus it broke on both desktop and mobile)

This link should normally work at this time, until we are able to fix this with Box:
https://auth.mozilla.auth0.com/samlp/yCKLKXrrkigZwoQ9d6xzmE5NuvVW0oBj (note, no sensitive data is stored in this URL - this is just an identifier for Box)

**Comment by jcook123** [comment] 2018-02-22 01:50
Cool thx for the quick feedback.    For the record, I had to turn to my laptop each time and the desktop version worked fine (laptop). But The “desktop version” on mobile (Firefox) never did
  

  
  

  
  
>

**Comment by gdestuynder** [comment] 2018-02-22 01:51
Box is working on this right now as far as I understand, so things may work again soon, and/or stop working/work again
Prior logins have a session established with Box, which is why they would still work until the session times out

**Comment by jcook123** [comment] 2018-02-22 01:53
I just tried the box iOS app again
  

  
Way diff error than before
  

  
Before error =   
  
  

  

  
CURENT ERROR =
  
  

  
  
  
  
  

  
  

  
  
>

**Comment by gdestuynder** [comment] 2018-02-22 18:03
It seems Box still has issues, so EUS has put a direct login option for now and is handling this directly with them in our internal tracking tools.
You can follow up ticket `INC0024708` in http://mozilla.service-now.com/

I'm closing this on our side for now

**Closed by gdestuynder** 2018-02-22 18:03 UTC
Labels: bug

**Comment by gene1wood** [comment] 2018-02-22 22:06
@jcook123 We're working under the assumption that what you saw was a problem logging into https://mozilla.box.com/ (and only Box.com) using your email address on mobile.

If you also had a problem logging into some other site, other than box.com from your phone, for example Google Mail, let us know and we can open a new issue and help figure out what the problem is.

**Comment by jcook123** [comment] 2018-02-22 22:19
My orig issue which still persists is any mobile box app from any mobile device does not work.  I encourage you to try it for yourself.   It continues to appear to be on our end...not Box’s end...as it gets through 2 factor auth...but the final handshake fails. (Something for sure has changed as it was working fine prior to this change)
Jim

**Comment by gene1wood** [comment] 2018-02-22 22:43
Got it, thank you for the details, I wanted to make sure the problem was constrained to box.com and not other sites. I've asked Soap in IRC to give an update on his work with box.com on this, we'll see what he says.

**Comment by sophanaaik** [comment] 2018-02-22 23:07
@jcook123 

Hi Jim, we've identified the root cause between Box and our SAML configuration. This affected the mobile login as well as the desktop login. Currently SSO is still turned off to allow people to login manually via PW. The SSO (and security) team implemented the change, and we will be turning it back on after hours at 5PM to see if it works again. I'll also make sure to test the mobile login on my own account as well. Thanks

**Comment by gdestuynder** [comment] 2018-02-23 01:04
Hi,
I believe this has been resolved cc @sophanaaik

**Comment by sophanaaik** [comment] 2018-02-23 01:14
@gdestuynder  @jcook123 

Confirmed I tested this on the desktop login, and the mobile login, it now works as expected. Thanks
