### ISSUE TITLE
"Invalid OAuth parameter: prompt" error when trying to verify fxa identity in mozillians

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#182] opened 2018-06-25 12:31 UTC
STR:
1. Login to http://web-mozillians-staging.production.paas.mozilla.community/
2. Navigate to settings page
3. Click "Add Identity" and select "Log in with Firefox"

Expected:
Enter credentials window is shown

Actual:
"Invalid OAuth parameter: prompt" error is shown

![add fxa in stage](https://user-images.githubusercontent.com/5293100/41850302-ba1de62a-788c-11e8-85b3-a5482aa69a40.png)

**Comment by viorelaioia** [comment] 2018-06-25 12:31
CC: @gdestuynder

**Comment by gdestuynder** [comment] 2018-06-25 20:36
this is a NLX regression - it's supposed to write the prompt parameter when using firefox account (this works fine in prod) @hidde

**Comment by gdestuynder** [comment] 2018-06-26 19:14
this seems to be what fxa triggers even when there is no `prompt` param issue, if the authentication fails.
it turns out to be an issue with the nodejs8 upgrade, fix at https://github.com/mozilla-iam/auth0-deploy/pull/205

**Comment by viorelaioia** [comment] 2018-06-27 10:29
This is still happening.

**Comment by gdestuynder** [comment] 2018-06-27 18:14
indeed, looks like we misdiagnosed this to the nodejs8 update.
nlx does a `prompt=select_account` and only blacklist `prompt=none` for FxA, but FxA supports neither

**Comment by hidde** [comment] 2018-06-28 09:37
Thanks for the clarification, @gdestuynder. I've looked at this a bit more, and we do not actually remove parameters for FxA (prompt=none or prompt=select_account). 

Currently we run the same NLX in DEV and PROD and there is no problem in PROD (Mozillians and therefore NLX is also passing the `prompt=select_account` parameter). This makes me think the issue is not in NLX. 

I have opened an [issue](https://github.com/mozilla/fxa-content-server/issues/6316) for this at `mozilla/fxa-content-server` and would like to close this one (feel free to reopen if you disagree 😄 )

**Comment by gdestuynder** [comment] 2018-06-28 22:49
The issue is not in NLX but fixable by NLX until FxA supports this

**Comment by gdestuynder** [comment] 2018-06-28 22:51
im reopening it to avoid new issues poping up reporting the same thing. 
lets close it when either nlx has a work-around or fxa implements the feature

**Comment by hidde** [comment] 2018-07-24 11:18
This now also happens in PROD, I suspect because either Auth0 update or a FxA update. I will PR to Mozillians to use a different parameter and non-standard. Least hacky way to fix this imho.

**Comment by hidde** [comment] 2018-07-24 14:53
@viorelaioia This is now fixed in STAGING, please verify.

**Comment by viorelaioia** [comment] 2018-07-25 12:03
Verified in staging, works as expected :+1:

**Closed** 2018-07-27 15:06 UTC
Labels: bug, verified
