### ISSUE TITLE
Clicking back from Google auth account picker locks user into Google auth flow

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#18] opened 2018-02-20 17:24 UTC
# Steps to reproduce

1. Browse to https://moderator.mozilla.org/oidc/authenticate/
2. Click Google
3. Arrive at the Google account picker
4. Click back

# Expected results

Get taken back to the lock

# Actual results

Stay on the Google account picker. Any further attempt to login to moderator skips the lock and sends you directly to the Google account picker so you're locked into this flow.

**Comment by gdestuynder** [comment] 2018-02-20 17:37
dupe of https://github.com/mozilla-iam/auth0-custom-lock/issues/17
this fails for the same reason

**Closed by gdestuynder** 2018-02-20 17:37 UTC
